name: 🚀 Publish Python package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      # 1. Chequea el código
      - uses: actions/checkout@v4

      # 2. Prepara Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Instala build y construye artefactos
      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build wheel and sdist
        run: |
          python -m build --sdist --wheel

      # 4. Publica en PyPI usando el token secreto
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
